### PR TITLE
Switch pause container to eks-d one

### PR DESCRIPTION
**Pull request by ktsakalozos**
Fixes https://github.com/canonical/eks-snap/issues/16

### CODE REVIEW

**Review by joedborg — APPROVED** [review]
LGTM

**Comment by pahud** [comment]
This is awesome! So we can deploy `eks snap` everywhere including China.

**Comment by pahud** [comment]
Hi, any chance we can fix the CI error and hopefully merge this PR?

**Comment by ktsakalozos** [comment]
> Hi, any chance we can fix the CI error and hopefully merge this PR?

Should be released soon. Thank you for keeping track of it.

**Comment by pahud** [comment]
> > Hi, any chance we can fix the CI error and hopefully merge this PR?
> 
> Should be released soon. Thank you for keeping track of it.

Awesome! It works! https://github.com/pahud/cdk-eksdistro/issues/2#issuecomment-773301041

**Pull request merged**
